### ISSUE TITLE
댓글 및 검색 프론트 합의

### ISSUE THREAD

**Issue by alicesykim95** [TRIPONG-2022/backend#8]
안녕하세요 정민님(@jma1020) 코드를 작성하기 앞서 프론트측과 명확하게 합의하고싶어 문의드립니다. 😊

### 📌 댓글

댓글 파트 먼저 여쭤볼게요. 

#### [댓글 / 대댓글 조회] 

- 우선 한가지 언급하자면 무한 댓글이 아닌 댓글-대댓글 형태로 진행하는 것으로 기억하고 있어요. 이를 기반으로 질문을 드릴게요. Figma를 확인해보니 댓글의 답글 버튼을 눌러서 숨겨져있는 답글을 확인하는 조회하는 형태가 아닌 댓글과 답글 모두 한번에 조회하는 형태더라구요. 혹시 데이터 전달시 댓글과 답글을 한번에 리스트로 전달하는 것이 좋을까요? 정민님께서 원하신는 데이터 전달 방법에 대해 여쭙고 싶습니다.

- 데이터를 끌어올때 내림차순 / 오름차순 순서 중 내림차순으로 합의 본 것으로 기억하는데 맞을까요? 
 
#### [댓글 / 대댓글 작성 + 수정 + 삭제]

- 댓글과 대댓글 작성하여 비동기로 전송하실때 각기 다른 요청을 보낼건지 아니면 하나의 요청을 보내서 백엔드측이 댓글과 대댓글을 구분해서 처리를 해야할지 궁금해요. 

- 수정과 삭제 역시 위와 동일한 질문을 하고싶습니다. 같은 요청을 보내실건지 아니면 다른 요청을 보내실건가요? 

- 삭제에서 부모 댓글 삭제시 자식 답글도 같이 삭제되는 형태로 가져가고 반대로 자식답글을 삭제해도 부모 댓글에 영향이 없는 형태로 가져가려고 하는데 괜찮을까요? 

### 📌 검색

다음은 검색 파트입니다. 제가 생각하는 검색 플로우를 말씀드릴게요. 

- 유저가 검색 창에서 검색 카테고리 선택 (제목/내용/유저이름) 및 검색 실행 → 각 카테고리 별로 DB에서 데이터 조회(백엔드) → 프론트로 데이터 전달

아마 제목과 내용 카테고리는 게시글의 특성에 상관없이 모두 나열되는 형태로 갈 듯하고, 유저이름은 유저 프로필이 나열되는 형태로 갈 듯해요. 여기서 다른걸 제안하고 싶거나 원하는 데이터 형태 등이 있다면 자유롭게 의견 부탁드릴게요. 

우선 제가 궁금한건 여기까지에요! 제가 여쭤본 것 외에도 개인적으로 그리고 있는 그림이 있다면 공유 및 질문 부탁드릴게요. 회신 기다리고 있겠습니다.

**Comment by jma1020** [comment]
## 댓글/대댓글 조회
- 여기서 저는 그냥 수연님 말씀주신 형태로 답글을 눌러서 숨겨져있는 답글 확인하는 형태로 변경하는 것도 좋아보입니다!  그래서 저는 일단 댓글리스트를 받고 해당 댓글에 답글 클릭 시 해당 답글의 리스트를 받아오는 형식으로 진행해도 좋을 것 같습니다!!
- 네넵 내림차순으로 입니다!

## 댓글 /대댓글 작성 + 수정 + 삭제
- 구분하면, 아마 parent_reply로 하실거 같은데, 번거로운 과정이 생기면 저희 쪽에서 다른 요청 고려해봐도 좋을 것 같습니다.
- 이것도 동일합니다
- 넵 좋습니다!

## 검색
- 수연님이 말씀해주신 지금 플로우 괜찮은 것 같은데, 저희 쪽에서 검색 부분 디자인이 하나도 없네요..  프론트 분들이랑 추가해 놓겠습니다!

**Comment by alicesykim95** [comment]
답변 감사합니다 정민님!(@jma1020) 

대체적으로 동의해주신 것 같아 언급한 플로우와 구조로 가져가도록 하겠습니다! 마지막으로 몇가지 부분에 대해 정리 및 질문을 드릴게요. 

#### 📌 댓글 

- 댓글 조회에 대해 총정리를 하면 아래와 같을 것 같네요. 혹시 서로 이해한 부분이 다르다면 다시 말씀해주세요! 
  - 게시글 상세 페이지 이동 → 상세페이지 출력과 동시에 댓글 리스트 출력(백엔드에서 전달/내림차순) → 댓글에서 답글 보기 클릭(프론트에서 답글 리스트 요청) → DB에서 답글 리스트 출력 및 프론트로 리다이렉트(백엔드/내림차순) → 답글 리스트 출력

-  이전에 REST API 설계서 만들 당시에 합의본 댓글과 답글 조회에 대한 URL입니다. 이대로 진행할 예정인데, 이견 있으시면 말씀해주세요! 
  - 댓글: replies/{postId}/root?page=0&size=20&sort=id,desc
  - 답글: replies/{postId}/{replyId}/children

- 개인적으로 댓글과 답글을 구분해서 요청보내주시는게 좋을 것 같아요! 그렇게 해주실 수 있으실까요? 하지만 정민님께서도 언급하셨듯 번거로운 과정이 생기거나 문제가 있다면 말씀해주세요! 언제든 문제없는 방향으로 수정이 가능합니다. 

- 이건 어제 틀을 짜면서 고민하다가 궁금해서 여쭤봐요. 혹시 댓글과 답글 총 갯수 데이터가 필요할까요? 

#### 📌 검색

- 검색 플로우는 동의하셨으니 그대로 진행할게요! 단지 검색 카테고리를 검색 키워드와 함께 넘겨주시면 좋을 듯 합니다. 예를 들어, '제목' 카테고리를 선택해서 '안녕'이라는 키워드를 검색했다면, {keyword='안녕', category='제목'} 이런식으로요!  



해당 글을 끝으로 플로우 및 전체적인 틀을 지난번 이메일 인증과 동일하게 Notion에 정리할 예정입니다. 후에 코드 작성하시면서 참고하시면 좋을 듯하고, 진행 중에 질문 및 변동사항에 대해 자유롭게 말씀해주세요!

**Comment by jma1020** [comment]
📌 댓글
- 넵 좋습니다! 
- 여기 궁금한 거 있어서 디코에서 간단하게 듣고 싶어서 디코 메세지 남겨 놓았습니다!

📌 검색
- 이 부분은 쿼리로 넘겨드리는 방식 생각하고 있었습니다


😀 정리해주셔서 감사합니다~~
